//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormulariosVideoclub.wsTransacciones {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsTransaccionesSoap", Namespace="http://tempuri.org/")]
    public partial class wsTransacciones : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback stInsertarTransaccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataTransOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarTransaccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarTransaccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTransaccionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsTransacciones() {
            this.Url = global::FormulariosVideoclub.Properties.Settings.Default.FormulariosVideoclub_wsTransacciones_wsTransacciones;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event stInsertarTransaccionesCompletedEventHandler stInsertarTransaccionesCompleted;
        
        /// <remarks/>
        public event GetDataTransCompletedEventHandler GetDataTransCompleted;
        
        /// <remarks/>
        public event BuscarTransaccionCompletedEventHandler BuscarTransaccionCompleted;
        
        /// <remarks/>
        public event actualizarTransaccionCompletedEventHandler actualizarTransaccionCompleted;
        
        /// <remarks/>
        public event eliminarTransaccionCompletedEventHandler eliminarTransaccionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/stInsertarTransacciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string stInsertarTransacciones(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total) {
            object[] results = this.Invoke("stInsertarTransacciones", new object[] {
                        id_tran,
                        id_producto,
                        id_empleado,
                        id_cliente,
                        Tipo_tran,
                        Cantidad,
                        fecha_registro,
                        MontoxDia,
                        Dias_renta,
                        fecha_entrega,
                        Total});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void stInsertarTransaccionesAsync(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total) {
            this.stInsertarTransaccionesAsync(id_tran, id_producto, id_empleado, id_cliente, Tipo_tran, Cantidad, fecha_registro, MontoxDia, Dias_renta, fecha_entrega, Total, null);
        }
        
        /// <remarks/>
        public void stInsertarTransaccionesAsync(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total, object userState) {
            if ((this.stInsertarTransaccionesOperationCompleted == null)) {
                this.stInsertarTransaccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstInsertarTransaccionesOperationCompleted);
            }
            this.InvokeAsync("stInsertarTransacciones", new object[] {
                        id_tran,
                        id_producto,
                        id_empleado,
                        id_cliente,
                        Tipo_tran,
                        Cantidad,
                        fecha_registro,
                        MontoxDia,
                        Dias_renta,
                        fecha_entrega,
                        Total}, this.stInsertarTransaccionesOperationCompleted, userState);
        }
        
        private void OnstInsertarTransaccionesOperationCompleted(object arg) {
            if ((this.stInsertarTransaccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stInsertarTransaccionesCompleted(this, new stInsertarTransaccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDataTrans() {
            object[] results = this.Invoke("GetDataTrans", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataTransAsync() {
            this.GetDataTransAsync(null);
        }
        
        /// <remarks/>
        public void GetDataTransAsync(object userState) {
            if ((this.GetDataTransOperationCompleted == null)) {
                this.GetDataTransOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataTransOperationCompleted);
            }
            this.InvokeAsync("GetDataTrans", new object[0], this.GetDataTransOperationCompleted, userState);
        }
        
        private void OnGetDataTransOperationCompleted(object arg) {
            if ((this.GetDataTransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataTransCompleted(this, new GetDataTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarTransaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarTransaccion(int id_tran) {
            object[] results = this.Invoke("BuscarTransaccion", new object[] {
                        id_tran});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarTransaccionAsync(int id_tran) {
            this.BuscarTransaccionAsync(id_tran, null);
        }
        
        /// <remarks/>
        public void BuscarTransaccionAsync(int id_tran, object userState) {
            if ((this.BuscarTransaccionOperationCompleted == null)) {
                this.BuscarTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarTransaccionOperationCompleted);
            }
            this.InvokeAsync("BuscarTransaccion", new object[] {
                        id_tran}, this.BuscarTransaccionOperationCompleted, userState);
        }
        
        private void OnBuscarTransaccionOperationCompleted(object arg) {
            if ((this.BuscarTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarTransaccionCompleted(this, new BuscarTransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarTransaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string actualizarTransaccion(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total) {
            object[] results = this.Invoke("actualizarTransaccion", new object[] {
                        id_tran,
                        id_producto,
                        id_empleado,
                        id_cliente,
                        Tipo_tran,
                        Cantidad,
                        fecha_registro,
                        MontoxDia,
                        Dias_renta,
                        fecha_entrega,
                        Total});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarTransaccionAsync(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total) {
            this.actualizarTransaccionAsync(id_tran, id_producto, id_empleado, id_cliente, Tipo_tran, Cantidad, fecha_registro, MontoxDia, Dias_renta, fecha_entrega, Total, null);
        }
        
        /// <remarks/>
        public void actualizarTransaccionAsync(long id_tran, long id_producto, long id_empleado, long id_cliente, string Tipo_tran, long Cantidad, string fecha_registro, long MontoxDia, long Dias_renta, string fecha_entrega, long Total, object userState) {
            if ((this.actualizarTransaccionOperationCompleted == null)) {
                this.actualizarTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarTransaccionOperationCompleted);
            }
            this.InvokeAsync("actualizarTransaccion", new object[] {
                        id_tran,
                        id_producto,
                        id_empleado,
                        id_cliente,
                        Tipo_tran,
                        Cantidad,
                        fecha_registro,
                        MontoxDia,
                        Dias_renta,
                        fecha_entrega,
                        Total}, this.actualizarTransaccionOperationCompleted, userState);
        }
        
        private void OnactualizarTransaccionOperationCompleted(object arg) {
            if ((this.actualizarTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarTransaccionCompleted(this, new actualizarTransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTransaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eliminarTransaccion(int id_transaccion) {
            object[] results = this.Invoke("eliminarTransaccion", new object[] {
                        id_transaccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTransaccionAsync(int id_transaccion) {
            this.eliminarTransaccionAsync(id_transaccion, null);
        }
        
        /// <remarks/>
        public void eliminarTransaccionAsync(int id_transaccion, object userState) {
            if ((this.eliminarTransaccionOperationCompleted == null)) {
                this.eliminarTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTransaccionOperationCompleted);
            }
            this.InvokeAsync("eliminarTransaccion", new object[] {
                        id_transaccion}, this.eliminarTransaccionOperationCompleted, userState);
        }
        
        private void OneliminarTransaccionOperationCompleted(object arg) {
            if ((this.eliminarTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTransaccionCompleted(this, new eliminarTransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void stInsertarTransaccionesCompletedEventHandler(object sender, stInsertarTransaccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stInsertarTransaccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stInsertarTransaccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataTransCompletedEventHandler(object sender, GetDataTransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarTransaccionCompletedEventHandler(object sender, BuscarTransaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarTransaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarTransaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarTransaccionCompletedEventHandler(object sender, actualizarTransaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarTransaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarTransaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarTransaccionCompletedEventHandler(object sender, eliminarTransaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTransaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTransaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591